export interface AssignmentEmailParams {
  recipientName: string
  taskTitle: string
  clientName: string
  confirmedDeadline: string | null
  estimatedHours: number | null
  directorName: string
  description: string | null
  taskUrl: string
  locale: 'ja' | 'en'
}

export function getAssignmentEmailHtml(params: AssignmentEmailParams): string {
  const {
    recipientName,
    taskTitle,
    clientName,
    confirmedDeadline,
    estimatedHours,
    directorName,
    description,
    taskUrl,
    locale,
  } = params

  const isJa = locale === 'ja'

  const labels = {
    headerTitle: isJa ? 'WorkFlow \u2014 \u30BF\u30B9\u30AF\u901A\u77E5' : 'WorkFlow \u2014 Task Notification',
    greeting: isJa
      ? `${recipientName}\u3055\u3093\u3001\u65B0\u3057\u3044\u30BF\u30B9\u30AF\u304C\u30A2\u30B5\u30A4\u30F3\u3055\u308C\u307E\u3057\u305F`
      : `Hi ${recipientName}, a new task has been assigned to you`,
    taskTitle: isJa ? '\u30BF\u30B9\u30AF\u540D' : 'Task Title',
    client: isJa ? '\u30AF\u30E9\u30A4\u30A2\u30F3\u30C8' : 'Client',
    deadline: isJa ? '\u7D0D\u54C1\u671F\u9650' : 'Deadline',
    estimatedHours: isJa ? '\u898B\u7A4D\u6642\u9593' : 'Estimated Hours',
    director: isJa ? '\u30C7\u30A3\u30EC\u30AF\u30BF\u30FC' : 'Director',
    description: isJa ? '\u8AAC\u660E' : 'Description',
    cta: isJa ? '\u30BF\u30B9\u30AF\u3092\u78BA\u8A8D\u3059\u308B \u2192' : 'View Task \u2192',
    notSet: isJa ? '\u672A\u8A2D\u5B9A' : 'Not set',
    hours: isJa ? '\u6642\u9593' : 'hours',
    footer: isJa
      ? '\u3053\u306E\u30E1\u30FC\u30EB\u306FWorkFlow\u30B7\u30B9\u30C6\u30E0\u304B\u3089\u81EA\u52D5\u9001\u4FE1\u3055\u308C\u3066\u3044\u307E\u3059\u3002\u8FD4\u4FE1\u306F\u3067\u304D\u307E\u305B\u3093\u3002'
      : 'This email was automatically generated by the WorkFlow system. Please do not reply.',
  }

  const deadlineDisplay = confirmedDeadline || labels.notSet
  const hoursDisplay =
    estimatedHours != null ? `${estimatedHours} ${labels.hours}` : labels.notSet
  const descriptionDisplay = description || labels.notSet

  return `<!DOCTYPE html>
<html lang="${locale}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${labels.headerTitle}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f4f4f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color: #f4f4f5; padding: 32px 0;">
    <tr>
      <td align="center">
        <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
          <!-- Header -->
          <tr>
            <td style="background-color: #6FB5A3; padding: 24px 32px;">
              <h1 style="margin: 0; color: #ffffff; font-size: 20px; font-weight: 600; letter-spacing: 0.5px;">
                ${labels.headerTitle}
              </h1>
            </td>
          </tr>

          <!-- Greeting -->
          <tr>
            <td style="padding: 32px 32px 16px 32px;">
              <p style="margin: 0; font-size: 16px; color: #18181b; line-height: 1.6;">
                ${labels.greeting}
              </p>
            </td>
          </tr>

          <!-- Task Details Table -->
          <tr>
            <td style="padding: 16px 32px;">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border: 1px solid #e4e4e7; border-radius: 6px; overflow: hidden;">
                <tr>
                  <td style="padding: 12px 16px; background-color: #f9fafb; border-bottom: 1px solid #e4e4e7; font-size: 13px; color: #71717a; font-weight: 600; width: 140px; vertical-align: top;">
                    ${labels.taskTitle}
                  </td>
                  <td style="padding: 12px 16px; border-bottom: 1px solid #e4e4e7; font-size: 14px; color: #18181b; font-weight: 600;">
                    ${escapeHtml(taskTitle)}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 12px 16px; background-color: #f9fafb; border-bottom: 1px solid #e4e4e7; font-size: 13px; color: #71717a; font-weight: 600; width: 140px; vertical-align: top;">
                    ${labels.client}
                  </td>
                  <td style="padding: 12px 16px; border-bottom: 1px solid #e4e4e7; font-size: 14px; color: #18181b;">
                    ${escapeHtml(clientName)}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 12px 16px; background-color: #f9fafb; border-bottom: 1px solid #e4e4e7; font-size: 13px; color: #71717a; font-weight: 600; width: 140px; vertical-align: top;">
                    ${labels.deadline}
                  </td>
                  <td style="padding: 12px 16px; border-bottom: 1px solid #e4e4e7; font-size: 14px; color: #18181b;">
                    ${escapeHtml(deadlineDisplay)}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 12px 16px; background-color: #f9fafb; border-bottom: 1px solid #e4e4e7; font-size: 13px; color: #71717a; font-weight: 600; width: 140px; vertical-align: top;">
                    ${labels.estimatedHours}
                  </td>
                  <td style="padding: 12px 16px; border-bottom: 1px solid #e4e4e7; font-size: 14px; color: #18181b;">
                    ${escapeHtml(hoursDisplay)}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 12px 16px; background-color: #f9fafb; border-bottom: 1px solid #e4e4e7; font-size: 13px; color: #71717a; font-weight: 600; width: 140px; vertical-align: top;">
                    ${labels.director}
                  </td>
                  <td style="padding: 12px 16px; border-bottom: 1px solid #e4e4e7; font-size: 14px; color: #18181b;">
                    ${escapeHtml(directorName)}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 12px 16px; background-color: #f9fafb; font-size: 13px; color: #71717a; font-weight: 600; width: 140px; vertical-align: top;">
                    ${labels.description}
                  </td>
                  <td style="padding: 12px 16px; font-size: 14px; color: #18181b; line-height: 1.5;">
                    ${escapeHtml(descriptionDisplay)}
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- CTA Button -->
          <tr>
            <td style="padding: 24px 32px;" align="center">
              <a href="${escapeHtml(taskUrl)}" target="_blank" style="display: inline-block; background-color: #6FB5A3; color: #ffffff; text-decoration: none; padding: 14px 32px; border-radius: 6px; font-size: 15px; font-weight: 600; letter-spacing: 0.3px;">
                ${labels.cta}
              </a>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding: 16px 32px 24px 32px; border-top: 1px solid #e4e4e7;">
              <p style="margin: 0; font-size: 12px; color: #a1a1aa; text-align: center; line-height: 1.5;">
                ${labels.footer}
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`
}

export interface CompletionEmailParams {
  recipientName: string
  taskTitle: string
  clientName: string
  completedByName: string
  estimatedHours: number | null
  actualHours: number | null
  taskUrl: string
  locale: 'ja' | 'en'
}

export function getCompletionEmailHtml(params: CompletionEmailParams): string {
  const {
    recipientName,
    taskTitle,
    clientName,
    completedByName,
    estimatedHours,
    actualHours,
    taskUrl,
    locale,
  } = params

  const isJa = locale === 'ja'

  const labels = {
    headerTitle: isJa ? 'WorkFlow — タスク完了通知' : 'WorkFlow — Task Completed',
    greeting: isJa
      ? `${recipientName}さん、タスクが完了しました`
      : `Hi ${recipientName}, a task has been completed`,
    taskTitle: isJa ? 'タスク名' : 'Task Title',
    client: isJa ? 'クライアント' : 'Client',
    completedBy: isJa ? '完了者' : 'Completed By',
    estimatedHours: isJa ? '見積時間' : 'Estimated Hours',
    actualHours: isJa ? '実績時間' : 'Actual Hours',
    cta: isJa ? 'タスクを確認する →' : 'View Task →',
    notSet: isJa ? '未設定' : 'Not set',
    hours: isJa ? '時間' : 'hours',
    footer: isJa
      ? 'このメールはWorkFlowシステムから自動送信されています。返信はできません。'
      : 'This email was automatically generated by the WorkFlow system. Please do not reply.',
  }

  const estimatedDisplay =
    estimatedHours != null ? `${estimatedHours} ${labels.hours}` : labels.notSet
  const actualDisplay =
    actualHours != null ? `${actualHours} ${labels.hours}` : labels.notSet

  return `<!DOCTYPE html>
<html lang="${locale}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${labels.headerTitle}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f4f4f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color: #f4f4f5; padding: 32px 0;">
    <tr>
      <td align="center">
        <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
          <!-- Header -->
          <tr>
            <td style="background-color: #22c55e; padding: 24px 32px;">
              <h1 style="margin: 0; color: #ffffff; font-size: 20px; font-weight: 600; letter-spacing: 0.5px;">
                ${labels.headerTitle}
              </h1>
            </td>
          </tr>

          <!-- Greeting -->
          <tr>
            <td style="padding: 32px 32px 16px 32px;">
              <p style="margin: 0; font-size: 16px; color: #18181b; line-height: 1.6;">
                ${labels.greeting}
              </p>
            </td>
          </tr>

          <!-- Task Details Table -->
          <tr>
            <td style="padding: 16px 32px;">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border: 1px solid #e4e4e7; border-radius: 6px; overflow: hidden;">
                <tr>
                  <td style="padding: 12px 16px; background-color: #f9fafb; border-bottom: 1px solid #e4e4e7; font-size: 13px; color: #71717a; font-weight: 600; width: 140px; vertical-align: top;">
                    ${labels.taskTitle}
                  </td>
                  <td style="padding: 12px 16px; border-bottom: 1px solid #e4e4e7; font-size: 14px; color: #18181b; font-weight: 600;">
                    ${escapeHtml(taskTitle)}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 12px 16px; background-color: #f9fafb; border-bottom: 1px solid #e4e4e7; font-size: 13px; color: #71717a; font-weight: 600; width: 140px; vertical-align: top;">
                    ${labels.client}
                  </td>
                  <td style="padding: 12px 16px; border-bottom: 1px solid #e4e4e7; font-size: 14px; color: #18181b;">
                    ${escapeHtml(clientName)}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 12px 16px; background-color: #f9fafb; border-bottom: 1px solid #e4e4e7; font-size: 13px; color: #71717a; font-weight: 600; width: 140px; vertical-align: top;">
                    ${labels.completedBy}
                  </td>
                  <td style="padding: 12px 16px; border-bottom: 1px solid #e4e4e7; font-size: 14px; color: #18181b;">
                    ${escapeHtml(completedByName)}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 12px 16px; background-color: #f9fafb; border-bottom: 1px solid #e4e4e7; font-size: 13px; color: #71717a; font-weight: 600; width: 140px; vertical-align: top;">
                    ${labels.estimatedHours}
                  </td>
                  <td style="padding: 12px 16px; border-bottom: 1px solid #e4e4e7; font-size: 14px; color: #18181b;">
                    ${escapeHtml(estimatedDisplay)}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 12px 16px; background-color: #f9fafb; font-size: 13px; color: #71717a; font-weight: 600; width: 140px; vertical-align: top;">
                    ${labels.actualHours}
                  </td>
                  <td style="padding: 12px 16px; font-size: 14px; color: #18181b;">
                    ${escapeHtml(actualDisplay)}
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- CTA Button -->
          <tr>
            <td style="padding: 24px 32px;" align="center">
              <a href="${escapeHtml(taskUrl)}" target="_blank" style="display: inline-block; background-color: #22c55e; color: #ffffff; text-decoration: none; padding: 14px 32px; border-radius: 6px; font-size: 15px; font-weight: 600; letter-spacing: 0.3px;">
                ${labels.cta}
              </a>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding: 16px 32px 24px 32px; border-top: 1px solid #e4e4e7;">
              <p style="margin: 0; font-size: 12px; color: #a1a1aa; text-align: center; line-height: 1.5;">
                ${labels.footer}
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}
