#!/usr/bin/env bash
# Generate Supabase database types from the remote project schema.
# Usage: npm run gen:types
# Prerequisites: npx supabase login

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="$PROJECT_ROOT/src/types/database.types.ts"

if [ -n "${SUPABASE_PROJECT_ID:-}" ]; then
  PROJECT_ID="$SUPABASE_PROJECT_ID"
else
  CONFIG_FILE="$PROJECT_ROOT/supabase/config.toml"
  if [ ! -f "$CONFIG_FILE" ]; then
    echo "Error: supabase/config.toml not found and SUPABASE_PROJECT_ID is not set." >&2
    exit 1
  fi
  PROJECT_ID=$(grep -E '^id\s*=' "$CONFIG_FILE" | sed 's/.*=\s*"\(.*\)"/\1/' | tr -d ' ')
  if [ -z "$PROJECT_ID" ]; then
    echo "Error: Could not read project id from supabase/config.toml" >&2
    exit 1
  fi
fi

echo "Generating types for project: $PROJECT_ID"
echo "Output: $OUTPUT_FILE"

GENERATED=$(npx supabase gen types typescript --project-id "$PROJECT_ID")

cat > "$OUTPUT_FILE" << HEADER
// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: npm run gen:types
// Source: Supabase project $PROJECT_ID
// Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
// To regenerate: npm run gen:types
// =============================================================================

HEADER

echo "$GENERATED" >> "$OUTPUT_FILE"

echo "Done. Types written to $OUTPUT_FILE"
